import { ContentItem, Fields, IContentItem } from 'kentico-cloud-delivery-typescript-sdk';

/**
 * This class was generated by 'kentico-cloud-model-generator-utility' module.
 * You can substitute instances of 'IContentItem' with a model defined in other class
 * to get access to all properties. This is applicable only if you know what item type the field contains.
 */
export class AssociateProfile extends ContentItem {
    public associateName: Fields.TextField;
    public associateTitle: Fields.TextField;
    public credentials: Fields.TextField;
    public associateStatus: Fields.TaxonomyField;
    public associateSummary: Fields.RichTextField;
    public developmentExperience: Fields.TaxonomyField;
    public methodologies: Fields.TaxonomyField;
    public functionalBusinessExperience: Fields.TaxonomyField;
    public industriesServed: Fields.TaxonomyField;
    public additionalTechnicalExperience: Fields.RichTextField;
    public clientFeedback: Fields.RichTextField;
    public results: Fields.RichTextField;
    public associateExperiences: IContentItem[];
    public education: Fields.RichTextField;
    public communityInvolvement: Fields.RichTextField;
    public technicalAndBusinessSkills: Fields.TaxonomyField;
    public certificationsAndProfessionalMemberships: Fields.TaxonomyField;
    public completeAssociateProfile: Fields.AssetsField;
    
    constructor(){
        super({
            propertyResolver: ((fieldName: string) => {
                
                if (fieldName === 'associate_name'){
                    return 'associateName';
                }

                if (fieldName === 'associate_title'){
                    return 'associateTitle';
                }

                if (fieldName === 'associate_status'){
                    return 'associateStatus';
                }

                if (fieldName === 'associate_summary'){
                    return 'associateSummary';
                }

                if (fieldName === 'development_experience'){
                    return 'developmentExperience';
                }

                if (fieldName === 'functional_business_experience'){
                    return 'functionalBusinessExperience';
                }

                if (fieldName === 'industries_served'){
                    return 'industriesServed';
                }

                if (fieldName === 'additional_technical_experience'){
                    return 'additionalTechnicalExperience';
                }

                if (fieldName === 'client_feedback'){
                    return 'clientFeedback';
                }

                if (fieldName === 'associate_experiences'){
                    return 'associateExperiences';
                }

                if (fieldName === 'community_involvement'){
                    return 'communityInvolvement';
                }

                if (fieldName === 'technical_and_business_skills'){
                    return 'technicalAndBusinessSkills';
                }

                if (fieldName === 'certifications_and_professional_memberships'){
                    return 'certificationsAndProfessionalMemberships';
                }

                if (fieldName === 'complete_associate_profile'){
                    return 'completeAssociateProfile';
                }

                return fieldName;
            })
        })    
    }
    
}