import { ContentItem, Fields } from 'kentico-cloud-delivery-typescript-sdk';

/**
 * This class was generated by 'kentico-cloud-model-generator-utility' module.
 * You can substitute instances of 'IContentItem' with a model defined in other class
 * to get access to all properties. This is applicable only if you know what item type the field contains.
 */
export class SkylineClient extends ContentItem {
    public name: Fields.TextField;
    public nickname: Fields.TextField;
    public description: Fields.RichTextField;
    public partnershipStartDate: Fields.DateTimeField;
    public industries: Fields.TaxonomyField;
    
    constructor(){
        super({
            propertyResolver: ((fieldName: string) => {
                
                if (fieldName === 'partnership_start_date'){
                    return 'partnershipStartDate';
                }

                return fieldName;
            })
        })    
    }
    
}