import { ContentItem, Fields, IContentItem } from 'kentico-cloud-delivery-typescript-sdk';
/**
 * This class was generated by 'kentico-cloud-model-generator-utility' module.
 * You can substitute instances of 'IContentItem' with a model defined in other class
 * to get access to all properties. This is applicable only if you know what item type the field contains.
 */
export class PortfolioItem extends ContentItem {
    public client: IContentItem[];
    public title: Fields.TextField;
    public subtitle: Fields.TextField;
    public friendlyUrl: Fields.UrlSlugField; 
    public description: Fields.RichTextField;
    public lengthOfEngagement: Fields.TextField;
    public actualLaunchDate: Fields.DateTimeField;
    public largeImage: Fields.AssetsField;
    public previewImage: Fields.AssetsField;
    public thumbnailImage: Fields.AssetsField;
    public features: IContentItem[];
    public technologies: IContentItem[];
    public testedPlatforms: IContentItem[];
    public deviceSections: IContentItem[];
    
    constructor(){
        super({
            propertyResolver: ((fieldName: string) => {
                
                if (fieldName === 'friendly_url'){
                    return 'friendlyUrl';
                }

                if (fieldName === 'length_of_engagement'){
                    return 'lengthOfEngagement';
                }

                if (fieldName === 'actual_launch_date'){
                    return 'actualLaunchDate';
                }

                if (fieldName === 'large_image'){
                    return 'largeImage';
                }

                if (fieldName === 'preview_image'){
                    return 'previewImage';
                }

                if (fieldName === 'thumbnail_image'){
                    return 'thumbnailImage';
                }

                if (fieldName === 'tested_platforms'){
                    return 'testedPlatforms';
                }

                if (fieldName === 'device_sections'){
                    return 'deviceSections';
                }

                return fieldName;
            })
        })    
    }
    
}