import { ContentItem, Fields } from 'kentico-cloud-delivery-typescript-sdk';

/**
 * This class was generated by 'kentico-cloud-model-generator-utility' module.
 * You can substitute instances of 'IContentItem' with a model defined in other class
 * to get access to all properties. This is applicable only if you know what item type the field contains.
 */
export class PortfolioItemTechnology extends ContentItem {
    public colorWithDropShadowIcon: Fields.AssetsField;
    public colorIcon: Fields.AssetsField;
    public blackWhiteIcon: Fields.AssetsField;
    public largeColorIcon: Fields.AssetsField;
    public largeBlackWhiteIcon: Fields.AssetsField;
    public technicalAndBusinessSkills: Fields.TaxonomyField;
    
    constructor(){
        super({
            propertyResolver: ((fieldName: string) => {
                
                if (fieldName === 'color_with_drop_shadow_icon'){
                    return 'colorWithDropShadowIcon';
                }

                if (fieldName === 'color_icon'){
                    return 'colorIcon';
                }

                if (fieldName === 'black___white_icon'){
                    return 'blackWhiteIcon';
                }

                if (fieldName === 'large_color_icon'){
                    return 'largeColorIcon';
                }

                if (fieldName === 'large_black___white_icon'){
                    return 'largeBlackWhiteIcon';
                }

                if (fieldName === 'technical_and_business_skills'){
                    return 'technicalAndBusinessSkills';
                }

                return fieldName;
            })
        })    
    }
    
}