import { ContentItem, Fields } from 'kentico-cloud-delivery-typescript-sdk';

/**
 * This class was generated by 'kentico-cloud-model-generator-utility' module.
 * You can substitute instances of 'IContentItem' with a model defined in other class
 * to get access to all properties. This is applicable only if you know what item type the field contains.
 */
export class PortfolioItemDeviceSectionColumn extends ContentItem {
    public classList: Fields.TextField;
    public content: Fields.RichTextField;
    
    constructor(){
        super({
            propertyResolver: ((fieldName: string) => {
                
                if (fieldName === 'class_list'){
                    return 'classList';
                }

                return fieldName;
            })
        })    
    }
    
}